version: '3.8'
services:
  bestpath:
    image: esp34-bestpath:latest
    ports:
    - "5000:5000"
    volumes:
    - .:/code
    - logvolume01:/var/log
    links:
    - redis
  redis:
    image: redis
volumes:
  logvolume01: {}